# Generated by Django 2.2.1 on 2019-05-11 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indie_theater', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='post',
            name='post_hit',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
