# Generated by Django 2.2.1 on 2019-05-11 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indie_theater', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CfPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('director', models.CharField(default='', max_length=50)),
                ('duration', models.IntegerField(default=0)),
                ('img', models.FileField(null=True, upload_to='')),
            ],
        ),
    ]
