# Generated by Django 2.2.1 on 2019-05-11 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indie_theater', '0002_auto_20190511_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_like',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
