# Generated by Django 2.2.1 on 2019-05-11 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indie_theater', '0004_cfpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='CfComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cfcontent', models.TextField()),
                ('cfpost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cfcomments', to='indie_theater.Post')),
            ],
        ),
    ]
