# Generated by Django 2.2.1 on 2019-05-11 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indie_theater', '0005_cfcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cfcomment',
            name='cfpost',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cfcomments', to='indie_theater.CfPost'),
        ),
    ]
