# Generated by Django 2.2.1 on 2019-05-11 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indie_theater', '0006_auto_20190511_1905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='rating1',
        ),
        migrations.RemoveField(
            model_name='post',
            name='rating2',
        ),
        migrations.RemoveField(
            model_name='post',
            name='rating3',
        ),
        migrations.AddField(
            model_name='comment',
            name='rating1',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3),
        ),
        migrations.AddField(
            model_name='comment',
            name='rating2',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3),
        ),
        migrations.AddField(
            model_name='comment',
            name='rating3',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3),
        ),
    ]
