# Generated by Django 2.2.1 on 2019-05-11 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indie_theater', '0007_auto_20190512_0536'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='rating1',
            new_name='시사성',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='rating2',
            new_name='예술성',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='rating3',
            new_name='창의성',
        ),
    ]
