# Generated by Django 2.2.1 on 2019-05-11 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indie_theater', '0008_auto_20190512_0543'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='내용',
        ),
        migrations.AlterField(
            model_name='comment',
            name='시사성',
            field=models.IntegerField(choices=[(1, '★'), (2, '★★'), (3, '★★★'), (4, '★★★★'), (5, '★★★★★')], default=3),
        ),
        migrations.AlterField(
            model_name='comment',
            name='예술성',
            field=models.IntegerField(choices=[(1, '★'), (2, '★★'), (3, '★★★'), (4, '★★★★'), (5, '★★★★★')], default=3),
        ),
        migrations.AlterField(
            model_name='comment',
            name='창의성',
            field=models.IntegerField(choices=[(1, '★'), (2, '★★'), (3, '★★★'), (4, '★★★★'), (5, '★★★★★')], default=3),
        ),
    ]
